CREATE DATABASE IF NOT EXISTS DAS_GestorPelis_db;
USE DAS_GestorPelis_db;

CREATE TABLE IF NOT EXISTS usuarios (
	id INT AUTO_INCREMENT PRIMARY KEY,
	password VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	foto VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS peliculas (
	id INT AUTO_INCREMENT PRIMARY KEY,
	titulo VARCHAR(255) NOT NULL,
	anno VARCHAR(4),
	genero VARCHAR(100),
	valoracion FLOAT,
	opinion TEXT,
	esFavorito TINYINT(1) DEFAULT 0,
	imagen VARCHAR(255),
	esPendiente TINYINT(1) DEFAULT 0,
	idUsuario INT NOT NULL,
	FOREIGN KEY (idUsuario) REFERENCES usuarios(id) ON DELETE CASCADE
) ENGINE=InnoDB;